### DISCUSSION TITLE
How to use python version in lock filename?

### DISCUSSION THREAD

**Discussion by ketozhang** [juftin/hatch-pip-compile#44] [Q&A] [answered]
Looking at hatch context variables documented in https://hatch.pypa.io/latest/config/environment/overview/ I can't seem to find a way to also write out the python version for the lock file.

**Comment by oprypin** [comment, marked as answer]
I think the only way to get the Python version is through the matrix.

Example how to get it into the env name -> into the lock filename:

```toml
[tool.hatch.envs.exampleenv]
type = "pip-compile"
[[tool.hatch.envs.exampleenv.matrix]]
python = ["3.11"]
```

I was also writing this example:

```toml
[tool.hatch.envs.exampleenv]
type = "pip-compile"
lock-filename = "requirements/requirements-{env_name}.{matrix:examplevarname}.txt"
[[tool.hatch.envs.exampleenv.matrix]]
examplevarname = ["3.11"]
```

but actually the latter part is redundant, the version is part of the env anyway and then it's part of the filename twice
