### ISSUE TITLE
universal locks across environments

### ISSUE THREAD

**Issue by juftin** [juftin/hatch-pip-compile#12]
## Summary

Hatch doesn't lock project dependencies universally across environments

## Details

In `hatch` a non-default environment also shares dependencies with the project dependencies.

consider the following `pyproject.toml`:

<details><summary>pyproject.toml</summary>
<p>

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  {name = "Justin Flannery", email = "juftin@juftin.com"}
]
dependencies = [
  "hatch"
]
version = "0.0.0"
license = "MIT"
name = "hatch-pip-compile"
readme = "README.md"
requires-python = ">=3.8"

[tool.hatch.env]
requires = ["hatch-pip-compile"]

[tool.hatch.envs.default]
path = ".venv"
post-install-commands = [
  "pre-commit install"
]
python = "3.11"
type = "pip-compile"
dependencies = ["pytest"]

[tool.hatch.envs.docs]
dependencies = [
  "mkdocs~=1.5.2",
  "mkdocs-material~=9.2.3",
  "mkdocstrings~=0.22.0",
  "markdown-exec[ansi]~=1.6.0"
]
type = "pip-compile"

[tool.hatch.envs.docs.scripts]
build = ["mkdocs build --clean --strict"]
deploy = ["mkdocs gh-deploy {args:}"]
serve = ["mkdocs serve --dev-addr localhost:8080 --livereload"]
```

</p>
</details> 

We can see there are three different sets of dependencies:

- Project Dependencies
    - hatch
- Default Dependencies
    - pytest
- Docs Dependencies
    - mkdocs~=1.5.2
    - mkdocs-material~=9.2.3
    - mkdocstrings~=0.22.0
    - markdown-exec[ansi]~=1.6.0

These groups of dependencies only make up two virtual environments though, `default` and `docs`. For both environments the project dependencies are also included (as long as the environment is not ["detached"](https://hatch.pypa.io/latest/config/environment/overview/#detached-environments)):

- `default` environment
    - hatch
    - pytest
- `docs` environment
    - hatch
    - mkdocs~=1.5.2
    - mkdocs-material~=9.2.3
    - mkdocstrings~=0.22.0
    - markdown-exec[ansi]~=1.6.0

The way `hatch-pip-compile` currently works is that it will create two lock files for these two environments but it is possible that the `hatch` dependency from the project will get pinned to a different version. Instead we want them to be pinned on the same version everywhere. 

## Proposed Solution

`hatch-pip-compile` should use the `default` environment's lockfile as a constraints file for other environments when running `pip-compile` (when the environment is not detached)

**Comment by FlorianWilhelm** [comment]
Thanks. Just out of curiosity, in your provided `pyproject.toml`, it says:
```
[tool.hatch.envs.default]
path = ".venv"
```
is `path` a parameter from hatch-pip-compile or is this a new feature of hatch. I guess the latter but cannot find in the docs. 
Does this mean I don't need to set globally in the config.toml
```
[dirs.env]
virtual = ".venv"
```
???

**Comment by juftin** [comment]
@FlorianWilhelm FYI - I'm actually just learning about 

```toml
[dirs.env]
virtual = ".venv"
```

Now that I'm learning about this I'm realizing that the following pattern will get inherited as the `default` template and you will end up with different environments writing to the `.venv` directory which is likely what you don't want

 
```toml 
[tool.hatch.envs.default]
path = ".venv"
```
