### ISSUE TITLE
Installation instructions not working

### ISSUE THREAD

**Issue by Tobi-De** [juftin/hatch-pip-compile#53]
Hi, 
I don't know where the issue is from but this code

```toml
[tool.hatch.env]
requires = [
    "hatch-pip-compile"
]
```
does not work, adding it make the pyproject.toml invalid and hatch fails to parse the file with `FileNotFoundError: [Errno 2] No such file or directory: '1'`, I'm on hatch latest version 1.9.1.
I also tried 

```toml
[build-system]
requires = ["hatchling", "hatch-pip-compile"]
build-backend = "hatchling.build"
```
but it seems to have no effect

**Comment by juftin** [comment]
Can you share your entire project.toml?

**Comment by Tobi-De** [comment]
> Can you share your entire pyproject.toml? Or even better, a link to the GitHub repository.

https://github.com/Tobi-De/vagabond

**Comment by Tobi-De** [comment]
I just tried hatch-pip-compile on a freshly generated hatch project and it worked no issue, now I'm more confused, the issue is definitively on my end, this is the pyproject content

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vagabond"
version = "0.1.0"
description = ''
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Tobi DEGNON", email = "tobidegnon@proton.me" }]
dependencies = [
  "Pillow>=10.1.0",
  "hiredis>=2.2.3",
  "redis>=5.0.1",
  "boto3>=1.26.160",
  "gunicorn",
  "sentry-sdk>=1.26.0",
  "whitenoise[brotli]>=6.5.0",
  "psycopg[c]",
  "django[argon2]>=4.2.0,<5.0",
  "django-environ>=0.10.0",
  "django-model-utils>=4.3.1",
  "django-allauth>=0.54.0",
  "django-template-partials>=23.4",
  "django-tailwind-cli>=2.7.2",
  "django-extensions>=3.2.3",
  "django-htmx>=1.15.0",
  "django-anymail>=10.0",
  "django-browser-reload>=1.10.0",
  "django-debug-toolbar>=4.1.0",
  "django-fastdev>=1.7.3",
]

[tool.hatch.env]
requires = [
    "hatch-pip-compile"
]

[tool.hatch.envs.default]
type = "pip-compile"
dependencies = ["dj-notebook>=0.6.1", "Werkzeug[watchdog]>=3.0.1"]

[tool.hatch.envs.default.scripts]
server = "python manage.py tailwind runserver {args}"
migrate = "python manage.py migrate {args}"
makemigrations = "python manage.py makemigrations {args}"
makesuperuser = "python manage.py makesuperuser"
reset-db = "python manage.py reset_db --noinput"
shell = "python manage.py shell_plus {args}"
reset-migrations = ["falco rm-migrations", "makemigrations"]

[[tool.hatch.envs.all.matrix]]
python = ["3.11", "3.12"]

[tool.hatch.envs.test]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest>=7.4.0",
  "pytest-django>=4.5.2",
  "pytest-sugar>=0.9.7",
]

[tool.hatch.envs.test.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = ["- coverage combine", "coverage report"]
cov = ["test-cov", "cov-report"]

[tool.hatch.envs.lint]
dependencies = [
  "pyright>=1.1.340",
  "curlylint>=0.13.1",
  "reorder-python-imports>=3.12.0",
  "djhtml>=3.0.6",
  "ruff>=0.1.8",
  "pyupgrade>=3.15.0",
  "django-upgrade>=1.15.0",
  "autoflake>=2.2.1",
]

[tool.hatch.envs.lint.scripts]
run-pyright = "pyright {args:.}"
run-format = "hatch fmt --formatter"
run-autoflake = "autoflake --in-place --remove-all-unused-imports --remove-unused-variables --expand-star-imports --exclude=.*/__init__.py {args:.}"
run-reorder-python-imports = "reorder-python-imports config/*.py {args:./*/*/*.py}"
run-ruff = "ruff check --quiet --fix --exit-non-zero-on-fix {args:.}"
run-curlylint = "curlylint {args:.}"
run-djhtml = "djhtml --tabwidth 4 {args:.}"
run-pyupgrade = "pyupgrade --py311-plus {args}"
run-all-pyupgrade = "git ls-files -- '*.py' | xargs pyupgrade --py311-plus"
run-django-upgrade = "django-upgrade --target-version 4.2 {args}"
run-all-django-upgrade = "git ls-files -- '*.py' | xargs django-upgrade --target-version 4.2"
python = [
  "run-pyright",
  "run-format",
  "run-reorder-python-imports",
  "run-autoflake",
  "run-ruff",
  "run-all-pyupgrade",
  "run-all-django-upgrade",
]
templates = ["run-curlylint", "run-djhtml"]
all = ["python", "templates"]

[tool.pyright]
typeCheckingMode = "basic"

[tool.curlylint]
include = '\.(html|jinja)$'
exclude = '''
(
  /(
      \.eggs           # exclude a few common directories in the root of the project
    | \.git
    | \.venv
    | \.ruff_cache
  )/
  | webpack-stats.html # also separately exclude a file named webpack-stats.html in the root of the project
)
'''

[tool.curlylint.rules]
indent = 4
aria_role = true
django_forms_rendering = true
image_alt = true
meta_viewport = true
no_autofocus = true
tabindex_no_positive = true

[tool.coverage.run]
source_pkgs = ["vagabond", "tests"]
branch = true
parallel = true
omit = ["src/vagabond/__about__.py"]

[tool.coverage.paths]
vagabond = ["src/vagabond", "*/vagabond/src/vagabond"]
tests = ["tests", "*/vagabond/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

```
The project is just a test project for me, don't bother trying to make it work

**Comment by juftin** [comment]
Hmmm... try deleting your `requirements.txt` file. On my end, I wasn't able to run anything because the default lockfile (`requirements.txt`) already existed but was generated with `pip-compile` and not `hatch-pip-compile` - so it didn't include the expected header. 

I also ran into issues with my machine on `psycopg[c]` so I just removed that in my test to get everything to work.

**Comment by Tobi-De** [comment]
> Hmmm... try deleting your `requirements.txt` file and let `hatch-pip-compile` regenerate it. On my end, I wasn't able to run anything because the default lockfile (`requirements.txt`) already existed but was generated with `pip-compile` and not `hatch-pip-compile` - so it didn't include the expected header.
> 
> I also ran into issues with my machine on `psycopg[c]` so I just removed that in my test to get everything to work.

I had the issue before I tried with pip-compile directly to generate a requirements.txt file.
Something weird just happened, the freshly generated hatch project that I was talking about just now, it was working fine, but I don't know how I managed to recreate the issue and I can't get it to work anymore

https://github.com/Tobi-De/fuko

**Comment by juftin** [comment]
What's the issue you're running into with `fuko`. I cloned the project, ran `hatch run python --version` and it created the lockfile no issue.

**Comment by Tobi-De** [comment]
> What's the issue you're running into with `fuko`. I cloned the project, ran `hatch run python --version` and it created the lockfile no issue.

please try with this exact content in the pyproject file

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fuko"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [
  { name = "Tobi DEGNON", email = "tobidegnon@proton.me" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "django",
]

[project.urls]
Documentation = "https://github.com/unknown/fuko#readme"
Issues = "https://github.com/unknown/fuko/issues"
Source = "https://github.com/unknown/fuko"

[tool.hatch.env]
requires = [
    "hatch-pip-compile"
]

[tool.hatch.envs.production]
type = "pip-compile"
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
lock-filename = "requirements.txt"

[tool.hatch.version]
path = "src/fuko/__about__.py"

[tool.hatch.envs.default]
type = "pip-compile"
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
lock-filename = "locks/default.lock"

[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/fuko tests}"

[tool.coverage.run]
source_pkgs = ["fuko", "tests"]
branch = true
parallel = true
omit = [
  "src/fuko/__about__.py",
]

[tool.coverage.paths]
fuko = ["src/fuko", "*/fuko/src/fuko"]
tests = ["tests", "*/fuko/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

```
