### ISSUE TITLE
Project missing in environment

### ISSUE THREAD

**Issue by FlorianWilhelm** [juftin/hatch-pip-compile#6]
Thanks for providing [hatch-pip-compile](https://github.com/juftin/hatch-pip-compile), it looks really useful but I am having a strange problem. Somehow the project itself is not installed in the default environment if it has type `"pip-compile"` as opposed to `"virtual"`. So in my `pyproject.toml` I have:

```toml
[tool.hatch.env]
requires = ["hatch-pip-compile"]  

[tool.hatch.envs.default]
type = "pip-compile"
[tool.hatch.envs.default.scripts]
upgrade-all = "pip-compile --upgrade {args}"
upgrade-pkg = "pip-compile --upgrade-package {args}"
```

and running `hatch run python -c "import name_of_my_package"` it doesn't find the package. Also `hatch run pip list` doesn't show it. Maybe I am missing something obvious here 🤔 .
