### ISSUE TITLE
Pinning packages to an index with `uv` does not work

### ISSUE THREAD

**Issue by valentinoli** [juftin/hatch-pip-compile#90]
`uv` supports [pinning a package to an index](https://docs.astral.sh/uv/configuration/indexes/#pinning-a-package-to-an-index). I tried this with `hatch` and it works:

```toml
[tool.hatch.envs.default]
installer = "uv"
dependencies = ["my-package"]

[tool.uv.sources]
my-package = { index = "foo" }

[[tool.uv.index]]
name = "foo"
url = "https://pkgs.dev.azure.com/foo/bar/_packaging/baz/pypi/simple/"
explicit = true
```

However, with `hatch-pip-compile` it does not work anymore:

```toml
[tool.hatch.envs.default]
type = "pip-compile"
pip-compile-resolver = "uv"
pip-compile-installer = "uv"
dependencies = ["my-package"]

[tool.uv.sources]
my-package = { index = "foo" }

[[tool.uv.index]]
name = "foo"
url = "https://pkgs.dev.azure.com/foo/bar/_packaging/baz/pypi/simple/"
explicit = true
```

I get an error that looks like:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because my-package was not found in the package registry and you require my-package, we can conclude
      that your requirements are unsatisfiable.
```

**Comment by juftin** [comment]
Is this a feature of `uv pip compile` or just uv projects?

**Comment by valentinoli** [comment]
It is a regular `uv` feature

https://docs.astral.sh/uv/configuration/indexes/#pinning-a-package-to-an-index

**Comment by juftin** [comment]
So it looks like the issue here is with explicit indexes. Since `hatch-pip-compile` uses a `requirements.in` file instead of a `pyproject.toml` file to generate LockFiles, it doesn't understand explicit indexes. 

Consider the following `requirements.in`:
```txt
uv~=0.6.3
test-123-test==1.0.0
```

`uv` comes from https://pypi.org/simple/, and `test-123-test` comes from https://test.pypi.org/simple/

So if you run `uv pip compile requirements.in` with the following `pyproject.toml` it will fail:
```toml
[tool.uv.sources]
test-123-test = { index = "test" }

[[tool.uv.index]]
name = "test"
url = "https://test.pypi.org/simple/"
explicit = true
```

```console
❯ uv pip compile requirements.in
  × No solution found when resolving dependencies:
  ╰─▶ Because test-123-test was not found in the package registry and you require test-123-test==1.0.0, we can conclude that your requirements are unsatisfiable.
```

However the following changes to the `pyproject.toml` will allow it to work:
```toml
[[tool.uv.index]]
name = "test"
url = "https://test.pypi.org/simple/"
```

```console
❯ uv pip compile requirements.in
Resolved 2 packages in 223ms
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in
test-123-test==1
    # via -r requirements.in
uv==0.6.3
    # via -r requirements.in
```

Unfortunately this is a bug (or maybe intended behavior?) on the `uv` side and not within `hatch-pip-compile`
